# web port
server:
  port: 8081

# log config
logging:
  config: classpath:logback.xml


### datax admin address list, such as "http://address" or "http://address01,http://address02"
datax:
  job:
    admin:
      ### datax-web admin address
      addresses: http://127.0.0.1:8080
    executor:
      appname: datax-executor
      ip:
      port: 9999
      ### job log path
      logpath:  D:\datax\\jobhandler
      ### job log retention days
      logretentiondays: 30
    ### job, access token
    accessToken:

  executor:
    jsonpath: D:\\datax\\executor\\json\\

  pypath: D:\\datax\\datax\\bin\\datax.py